🚧  WIP 🚧  Adding Exports-API documentation
myemma/emma-api-documentation pull request #29
Opened 2019-09-13 21:55 UTC by meganemorris

Documenting the Exports API in its own section.

2019-09-16 21:27 UTC, biggert requested changes
We should probably remove the exports section under members with this new section - http://localhost:63342/emma-api-documentation/api/external/members.html#get--#account_id-exports

2019-09-16 21:27 UTC, biggert commented on api/external/exports.html
> +<dt id="post--#account_id-exports">
In addition to getting the information about a created export, I believe this endpoint will be pretty popular so showing an example of the payload with a few parameters might be helpful to avoid some support calls.

2019-09-16 21:27 UTC, biggert commented on api/external/exports.html
> +        "status": "o",
let's add a small comment about the different types of statuses here. Here's an example of what we do for imports:
```
"status": "o", # for okay (or "e" for error, "q" for queued, "p" for in progress),
```

I think exports is limited to o, e, and p.

2019-09-16 21:27 UTC, biggert commented on api/external/exports.html
> +    "status": "o",
see other comment about explaining valid statuses

2019-09-16 22:09 UTC, meganemorris commented on api/external/exports.html
> +<dt id="post--#account_id-exports">
Added an example, but I can't see a preview of what's hidden under the `show` tag so a looksee would be helpful here, por favor.

2019-09-17 17:59 UTC, meganemorris commented
All requested changes have been made, I believe. Ready for another 👀 , please, and then should be good to go?

2019-09-17 18:19 UTC, biggert approved these changes
I noticed that the search functionality doesn't work for exports. We can iterate on that but I wonder if that's an easy fix? No showstoppers though so this PR on its own is shippable!

2019-09-17 18:19 UTC, biggert commented on api/external/exports.html
> +        "user_id": "1",
We could use a fake email address here as a better example since that's typically what shows up when you create an export via the UI but that's no showstopper

2019-09-17 20:52 UTC, meganemorris commented on api/external/exports.html
> +        "user_id": "1",
I concur.

2019-09-17 21:55 UTC, merged