🚧  WIP 🚧  Adding documentation for subscriptions-api to public documentation
myemma/emma-api-documentation pull request #30
Opened 2019-09-23 21:32 UTC by meganemorris

2019-09-26 21:24 UTC, biggert requested changes
All the samples LGTM!

2019-09-26 21:24 UTC, biggert commented on api/external/subscriptions.html
> +<li><strong>deleted_only</strong> &#8211; true or false. Defaults to false if neither is specified.</li>
Let's use the same format as we do in [here](http://localhost:63342/emma-api-documentation/api/external/groups.html#get--#account_id-groups-#member_group_id-members):
```
<li><strong>deleted_only</strong> &#8211; Only return deleted subscriptions. Optional, defaults to false.</li>
```

Same for the one below (obviously different subscription)

2019-09-26 21:24 UTC, biggert commented on api/external/subscriptions.html
> +<tt class="descname">GET </tt><tt class="descname">/#account_id/subscriptions/#subscription_id/members</tt><a class="headerlink" href="#get--#account_id-subscriptions-#subscription_id-members" title=
this section appears to be repeated

![image](https://user-images.githubusercontent.com/4029296/65725957-7cbdf800-e079-11e9-86f8-b2a7bbc8a7de.png)

2019-09-26 21:24 UTC, biggert commented on api/external/subscriptions.html
> +<li><strong>name</strong> (<em>string</em>) &#8211; Required.</li>
I know it is self-explanatory but we should probably describe what the `Name` field is used for.

As I typed that, I realized that we should probably point out that the name and description will be visible to on the subscription center

2019-09-26 21:24 UTC, biggert commented on api/external/subscriptions.html
> +<dd><p>Archive a subscription.</p>
Let's avoid the archive terminology here since we don't show that in the UI (nor allow them to unarchive).

`Delete a subscription.` should be fine

2019-09-27 16:33 UTC, meganemorris commented
Ok, I believe I've made all requested changes!

2019-09-27 16:36 UTC, biggert approved these changes
😹

2019-09-27 16:38 UTC, merged