CRM-5237: Update documentation to include sms
myemma/emma-api-documentation pull request #49
Opened 2023-11-17 16:52 UTC by epeatfield

2023-11-17 18:12 UTC, bhenry approved these changes
lgtm. i don't know how important the `link rel` stuff from the `head` should be. my guess is that it's not matched up in other files too.

2023-11-17 18:12 UTC, bhenry commented on api/external/sms.html
> +    <link rel="prev" title="Subscriptions" href="subscriptions.html" />
are we wanting to line these up with the other changes you made to subscriptions and signup_forms?

2023-11-17 19:43 UTC, Streeter8 commented on api/external/sms.html
> +    <link rel="prev" title="Subscriptions" href="subscriptions.html" />
That's a good point. It looks like we'd need to update these similar links in [the other templates](https://github.com/myemma/emma-api-documentation/blob/8438cf978505da94c63eb2ea01c733b2adf35c6d/api/external/signup_forms.html#L32-L33) too

2023-11-17 19:47 UTC, Streeter8 commented on api/external/sms.html
> +    <link rel="prev" title="Subscriptions" href="subscriptions.html" />
I guess we'd only need to update Webhooks, Subscriptions looks correct here

```suggestion
    <link rel="next" title="Signup Forms" href="signup_forms.html" />
    <link rel="prev" title="Subscriptions" href="subscriptions.html" />
```

2023-11-17 19:48 UTC, Streeter8 requested changes
We'll want to look at the prev/next links on these three pages. The descriptions look good on the endpoints themselves though, so the main stuff here looks good!

2023-11-17 20:31 UTC, epeatfield commented on api/external/sms.html
> +    <link rel="prev" title="Subscriptions" href="subscriptions.html" />
dang I missed one lol

2023-11-17 20:58 UTC, Streeter8 approved these changes
I think this is good now!

2023-11-17 21:00 UTC, Streeter8 commented
This is out of scope for this ticket, but if had a moment, we could fix [the navigation on the searches page](https://github.com/myemma/emma-api-documentation/blob/436e1d8c7c4caa66da6445ed1ac70bb8fe10ea57/api/external/searches.html#L33). The previous value should be response exports (similar to [this](https://github.com/myemma/emma-api-documentation/pull/36/files#diff-23d5a7e07f77860f38020e9fd7bcc3c5e5c1090fe13509120966e3ecd41adfb3R31)), but it seems we missed that in the related PR, #36. Definitely not a requirements on this PR though.

2023-11-20 18:18 UTC, Streeter8 approved these changes

2023-12-07 15:42 UTC, merged